<a href="https://colab.research.google.com/github/BarryLiu-97/Python/blob/master/numpy_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

导入numpy模块

In [0]:
array = np.array([[1,2,3],                
          [2,3,4]])   #创建numpy矩阵
print(array)
print('dimension:', array.ndim)  #矩阵维度
print('shape:', array.shape)   #矩阵形状
print('size', array.size)     #矩阵大小

In [6]:
a = np.array([2,3,4], dtype=np.int32) 
print(a.dtype)

int64


dtype:int 默认64位 float 默认64位
   int16 int32 float16 float32

In [0]:
zero_matrix = np.zeros((3,5))
print(zero_matrix)

创建3*5的元素都为0的矩阵

In [0]:
one_matrix = np.ones((3,5), dtype = np.int16)
print(one_matrix)

创建3*5的元素都为1的矩阵

In [0]:
empty_matrix = np.empty((3,6))
print(empty_matrix)

创建3*5的元素为空的矩阵，其实生成的是十分接近于0的元素不懂为什么用Colab时候矩阵大小设置为3×5生成的是元素为1的矩阵，但是用Spyder等还是OK的。

In [0]:
range_matrix = np.arange(10,20,2)
print(range_matrix)

In [0]:
range_matrix_2 = np.arange(12).reshape((3,4))
print(range_matrix_2)

In [0]:
line_matrix = np.linspace(1,10,5, dtype = np.float32)
print(line_matrix)

生成一个线段，起始为1，终止为10，一共生成5个点

In [55]:
a = np.array([10,20,30,40])
b = np.arange(4)
c = a + b
print(c)
d = a - b
print(d)
e = b**2
print(e)
f = 10*np.sin(a)
print(f)

[10 21 32 43]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
