<a href="https://colab.research.google.com/github/BarryLiu-97/Python/blob/master/numpy_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

导入numpy模块

In [136]:
array = np.array([[1,2,3],                
          [2,3,4]])   #创建numpy矩阵
print(array)
print('dimension:', array.ndim)  #矩阵维度
print('shape:', array.shape)   #矩阵形状
print('size', array.size)     #矩阵大小

[[1 2 3]
 [2 3 4]]
dimension: 2
shape: (2, 3)
size 6


In [137]:
arr_0 = np.array([2,3,4], dtype=np.int32) 
print(arr_0.dtype)

int32


dtype:int 默认64位 float 默认64位
   int16 int32 float16 float32

In [138]:
zero_matrix = np.zeros((3,5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


创建3*5的元素都为0的矩阵

In [139]:
one_matrix = np.ones((3,5), dtype = np.int16)
print(one_matrix)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


创建3*5的元素都为1的矩阵

In [140]:
empty_matrix = np.empty((3,6))
print(empty_matrix)

[[2.58147324e-316 2.14321575e-312 2.35541533e-312 1.48539705e-312
  2.48273508e-312 2.12199579e-312]
 [2.41907520e-312 2.35541533e-312 8.48798317e-313 2.05833592e-312
  2.18565567e-312 9.33678149e-313]
 [8.91238232e-313 2.27053550e-312 2.05833592e-312 2.18565567e-312
  8.70018275e-313 6.95003478e-310]]


创建3*5的元素为空的矩阵，其实生成的是十分接近于0的元素不懂为什么用Colab时候矩阵大小设置为3×5生成的是元素为1的矩阵，但是用Spyder等还是OK的。

In [141]:
range_matrix = np.arange(10,20,2)
print(range_matrix)

[10 12 14 16 18]


In [142]:
range_matrix_2 = np.arange(12).reshape((3,4))
print(range_matrix_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [143]:
line_matrix = np.linspace(1,10,5, dtype = np.float32)
print(line_matrix)

[ 1.    3.25  5.5   7.75 10.  ]


生成一个线段，起始为1，终止为10，一共生成5个点

In [144]:
a = np.array([10,20,30,40])
b = np.arange(4)
c = a + b
print(c)
d = a - b
print(d)
e = b**2
print(e)
f = 10*np.sin(a)  #cos、tan同样形式
print(f)
g = b < 3  # 同理 > 和 ==
print(g)

[10 21 32 43]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]


In [145]:
arr_1 = np.array([[1,1],[0,1]])
arr_2 = np.arange(4).reshape((2,2))
arr_3 = arr_1 * arr_2      #对应位置元素相乘
arr_4_dot = np.dot(arr_1,arr_2)  #矩阵乘法
print(arr_3)    
print(arr_4_dot)  

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [146]:
arr_5_dot = arr_1.dot(arr_2)  #矩阵相乘另一种写法
print(arr_5_dot)

[[2 4]
 [2 3]]


In [147]:
arr_6 = np.random.random((2,4))
print(arr_6)
print(np.sum(arr_6))
print(np.min(arr_6))
print(np.max(arr_6))
print(np.sum(arr_6,axis=0))  #axis= 0按列 1按行

[[0.11640608 0.19899625 0.55286632 0.50931998]
 [0.98216205 0.80742526 0.7536469  0.04059441]]
3.9614172490989032
0.04059440799848002
0.982162045731553
[1.09856813 1.00642151 1.30651322 0.54991439]


In [148]:
arr_7 = np.arange(14,2,-1).reshape((3,4))
print(arr_7)
print('最小值：', np.argmin(arr_7))   #最小值
print('最大值：', np.argmax(arr_7))   #最大值
print('按行计算均值：', np.mean(arr_7, axis=1))    #均值
print('均值：', np.average(arr_7))  #均值
print('均值：', arr_7.mean())     #均值
print('中位数：', np.median(arr_7))   #中位数
print(np.cumsum(arr_7))
print('查找非零元素：', np.nonzero(arr_7))   #输出非0元素的位置，前者为行号后者为列号
print('排序：', np.sort(arr_7))     #元素排序
print('转置：', np.transpose(arr_7))  #转置
print('转置：', arr_7.T)        #转置
print('转置并做矩阵乘法：', (arr_7.T).dot(arr_7))
print(np.clip(arr_7,5,9))        #小于5的数设为5，大于9的数设为9，其余不变

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
最小值： 11
最大值： 0
按行计算均值： [12.5  8.5  4.5]
均值： 8.5
均值： 8.5
中位数： 8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
查找非零元素： (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
排序： [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
转置： [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
转置： [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
转置并做矩阵乘法： [[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [149]:
arr_8 = np.arange(3,15).reshape((3,4))
print(arr_8)
print('矩阵的第二行的数：',arr_8[2])   #python从0开始计数
print('两种索引写法：',arr_8[2][1], arr_8[2,1])
print('第一列所有数：', arr_8[:,1])    

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
矩阵的第二行的数： [11 12 13 14]
两种索引写法： 12 12
第一列所有数： [ 4  8 12]


In [150]:
for row in arr_8:
  print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


按行迭代

In [151]:
for column in arr_8.T:
  print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


通过转置的方式进行按列迭代

In [152]:
print(arr_8.flatten())   #按行化为一维矩阵，并返回一个矩阵
for item in arr_8.flat:
  print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [0]:
arr_9 = np.array([1,1,1])
arr_10 = np.array([2,2,2])

In [154]:
vstack_arr = np.vstack((arr_9,arr_10))   #vertical stack 按行上下合并
hstack_arr = np.hstack((arr_9,arr_10))   #horizontal stack 按列左右合并
print(vstack_arr) 
print(hstack_arr) 
print(arr_9.shape, vstack_arr.shape, hstack_arr.shape)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (2, 3) (6,)


vstack、hstack可多矩阵合并

In [155]:
print(arr_9[np.newaxis,:], arr_9[np.newaxis,:].shape)
print(arr_9[:,np.newaxis], arr_9[:,np.newaxis].shape)

[[1 1 1]] (1, 3)
[[1]
 [1]
 [1]] (3, 1)


In [156]:
array_con = np.concatenate((arr_9,arr_9,arr_10))
print(array_con)
array_con_1 = np.concatenate((arr_9[:,np.newaxis],arr_9[:,np.newaxis],arr_10[:,np.newaxis]),axis=1)
print(array_con_1)

[1 1 1 1 1 1 2 2 2]
[[1 1 2]
 [1 1 2]
 [1 1 2]]


concatenta可以在后面直接设置以何种方式合并，默认左右合并

In [157]:
A = np.arange(12).reshape(3,4)
print(A)
print(np.split(A,2,axis=1))   #按列进行分割，每块两列
print(np.array_split(A,3,axis=1)) #不等分割
print(np.vsplit(A,3))  #按行分割
print(np.hsplit(A,2))  #按列分割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [158]:
B = np.arange(4)
print(B)
C = B
D = B
E = C
B[0] = 11
print(B,C,D,E)
print(B is E)
C[1:3] = [22,33]
print(B,C,D,E)

[0 1 2 3]
[11  1  2  3] [11  1  2  3] [11  1  2  3] [11  1  2  3]
True
[11 22 33  3] [11 22 33  3] [11 22 33  3] [11 22 33  3]


numpy中'='使得B、C、D、E是同一个东西，指向同一个地址，所以B改变了，所有的都改变了,称为浅copy

In [159]:
C_1 = B.copy()
print(C_1)
B[0] = 100
print(B,C_1)

[11 22 33  3]
[100  22  33   3] [11 22 33  3]


深copy，B改变不会影响C_1